### ISSUE TITLE
RTL Nova

### ISSUE THREAD

**Issue by FaridAghili** [zareismail/nova-trust#1]
سلام
تو اسکرین شات هایی که گذاشتید دیدم که گویا نوا رو راست به چپ کردید
https://novapackages.com//storage/screenshots/gaszcgRwEjL0VEUkjVC5rSTIZO8PdXFZ1o7q8ys0.png
https://novapackages.com//storage/screenshots/rkC6AW6ZExwMdaxRkIhJ3PHDbLTp4sDXrrFa5C1B.png
میشه بپرسم چطور؟

**Comment by zareismail** [comment]
> سلام
> تو اسکرین شات هایی که گذاشتید دیدم که گویا نوا رو راست به چپ کردید
> https://novapackages.com//storage/screenshots/gaszcgRwEjL0VEUkjVC5rSTIZO8PdXFZ1o7q8ys0.png
> https://novapackages.com//storage/screenshots/rkC6AW6ZExwMdaxRkIhJ3PHDbLTp4sDXrrFa5C1B.png
> میشه بپرسم چطور؟

سلام.
فک کنم با پکیج خودتون
