### ISSUE TITLE
Missing helper functions

### ISSUE THREAD

**Issue by saiik** [zareismail/nova-trust#2]
Hey,
I've just installed your package and some functions don't work for me.

For example the permission tab doesn't work, because some helper functions are missing:

- title_case / snake_case

Currently using Laravel Nova 2.0 and Laravel 6.X.

My fix would be:

File: Helpers/PermissionContainer.php

```php
	/**
	 * Make displayable name for ability.
	 * 
	 * @param  string $ability 
	 * @return string          
	 */
	static public function displayName(string $ability)
	{
		$ability = str_replace('-', ' ', $ability);

		$name = collect(explode('.', $ability))->reverse()->filter()->implode(' ');

		return Str::title(Str::snake($name, ' '));
	}
```

**Comment by saiik** [comment]
To be honest, there are a lot bugs right now. I forked your repo and fixed them.

**Comment by zareismail** [comment]
hi.thanks for your help

**Comment by deeaka** [comment]
I have install this package , and want to login without declare isDeveloper() function

**Comment by deeaka** [comment]
After install this package in novaServiceProvider.php function name gate()  is also not working
protected function gate()
    {
        Gate::define('viewNova', function ($user) {
            return $user->hasRole('nova-admin', 'nova-users');
        });
    }
