### ISSUE TITLE
undefined **title_case**  and  **snake_case** Error

### ISSUE THREAD

**Issue by wangbinyu** [zareismail/nova-trust#4]
In NovaTrust\Helpers\PermissionContainer  method at displayName

undefined **title_case**  and  **snake_case**

static public function displayName(string $ability)
	{
		$ability = str_replace('-', ' ', $ability);

		$name = collect(explode('.', $ability))->reverse()->filter()->implode(' ');

		return title_case(snake_case($name, ' '));
	}

**Comment by zareismail** [comment]
hi. use new release(0.2.2)
