### ISSUE TITLE
Migrations being added despite not running migration publish

### ISSUE THREAD

**Issue by ejntaylor** [zareismail/nova-trust#8]
I've already got my migrations in place for Team and Roles and so forth with additional customisations.

Now I'm adding this pacakge after a setup site I'm having the migration files from the vendor directory added automatically despite not being in my migrations/ folder.. 

Consequently I get a conflict:

`
Migrating: 2020_04_09_135211_create_team_table

   Illuminate\Database\QueryException

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'teams' already exists`

Any thoughts on how I stop the package from insisting on the migrations? I feel this is the final block to me using this package!

Cheers!

**Comment by zareismail** [comment]
hi. solution not exists. because you have the same migrations
